# -*- coding: utf-8 -*-
"""Personal Expense Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1us9mBvmIVq3uPcgVC5nmLm2ytF4tv0h3

#**Project Overview**

 **The `Personal Expense Tracker` is a command-line based Python application designed to help users securely record, manage, and analyze their daily expenses. The project supports `multiple users`, each with their own expense data stored in separate CSV files. Users can `sign up, log in, update their username or password`, add expenses with relevant details, view all records in a clean tabular format, filter expenses, delete incorrect entries, and generate monthly summaries.**




 **This project demonstrates practical usage of Python fundamentals, `data handling with Pandas, file-based persistence using CSV files`, and `user authentication for multi-user support`.**

#**Problem Statement**

**Many individuals struggle to track their daily or monthly spending. Manual tracking is often inefficient, error-prone, and lacks accountability. Additionally, users may share accounts or forget credentials, causing loss of data.**


**This project addresses these problems by providing a `secure, automated, and structured system` that allows multiple users to maintain `personalized expense records` safely, while supporting credential updates without data loss..**

##**Objective**



---


**The Personal Expense Tracker is a Python-based application designed to help users:**




---


- **Create a secure account (Sign Up / Login) and update credentials without losing data**
- **Add daily expenses with details like date, category, description, and amount**
- **View all recorded expenses in a clean, tabular format**
- **Delete unwanted or incorrect expense records safelye**
- **Filter expenses by category or date**
- **Generate monthly expense summaries for budgeting and analysis**
- **Maintain per-user CSV storage for persistent, secure data**
- **Exit the program gracefully**

#**Technologies**:
* **Python – Core programming**

* **Pandas – Data storage, manipulation, and analysis**

* **Tabulate – Pretty printing tables in CLI(Command-Line Interface.)**

* **CSV – File-based persistent storage**

* **JSON – User credentials and authentication**

#**End-User Value** :   

* **Helps manage personal finances efficiently.**

* **Provides insights into spending habits.**

* **Enables budget planning and monthly analysis.**

* **Ensures data privacy and secure multi-user support.**

* **Offers a robust and safe mechanism for updating credentials without losing historical data.**

#**Step-by-Step Explanation**


1.**`Requirement Analysis` – Decide key features: Sign Up / Login, Add, View, Delete, Filter, Monthly Summary, Update Account**

2.**`Data Storage Setup` – Create per-user CSV files for expense data and JSON file for storing credentials**

3.**`User Authentication` – Implement Login, Sign Up, Update Username & Password to ensure multi-user support and secure access**

4.**`Expense Management Functions` – Implement Add Expense, View Expenses, Delete Expenses**

5.**`Data Analysis Functions` – Filter expenses by category or date, generate monthly summaries**

6.**`Menu Interface` – Menu-driven CLI for user-friendly interaction**

7.**`Persistent Data Handling` – All user data saved in CSV and credentials in JSON, ensuring historical data is safe**

8.**`Exit and Account Management` – Graceful exit, with ability to manage account settings anytime**

#**Step 1 – Install Required Library**
"""

!pip install tabulate

"""#**Step 2 – Import Libraries**"""

import pandas as pd
import os
import json
from tabulate import tabulate

"""#**Step 3 – Create Users File**"""

users_file = "users.json"

if not os.path.exists(users_file):
    default_users = {
        "admin": "admin123"  # Default admin account
    }
    with open(users_file, "w") as f:
        json.dump(default_users, f)

"""#**Step 4 – Sign Up Function**"""

def sign_up():
    with open(users_file, "r") as f:
        users = json.load(f)

    print("\n---- Create a New Account ----")
    while True:
        username = input("Enter a new username: ").strip()
        if username in users:
            print("Username already exists! Try a different one.")
        elif username == "":
            print("Username cannot be empty.")
        else:
            break

    while True:
        password = input("Enter a new password: ").strip()
        confirm_password = input("Confirm password: ").strip()
        if password == "":
            print("Password cannot be empty.")
        elif password != confirm_password:
            print("Passwords do not match! Try again.")
        else:
            break

    users[username] = password
    with open(users_file, "w") as f:
        json.dump(users, f)

    print(f"Account created successfully! You can now login as '{username}'\n")

"""#**Step 5 – Login Function**"""

def login():
    with open(users_file, "r") as f:
        users = json.load(f)

    print("\n---- Login ----")
    username = input("Username: ").strip()
    password = input("Password: ").strip()

    if username in users and users[username] == password:
        print(f"Login successful! Welcome, {username}.\n")
        return username
    else:
        print("Invalid credentials. Try again.\n")
        return None

# Step 5a – Update Password
def update_password(username):
    with open(users_file, "r") as f:
        users = json.load(f)

    old_pwd = input("Enter old password: ").strip()
    if users.get(username) != old_pwd:
        print("Old password incorrect!")
        return

    new_pwd = input("Enter new password: ").strip()
    confirm_pwd = input("Confirm new password: ").strip()

    if new_pwd != confirm_pwd:
        print("Passwords do not match!")
        return

    users[username] = new_pwd
    with open(users_file, "w") as f:
        json.dump(users, f)

    print("Password updated successfully!")

# Step 5b – Update Username
def update_username(old_username):
    with open(users_file, "r") as f:
        users = json.load(f)

    new_username = input("Enter new username: ").strip()
    if new_username in users:
        print("Username already exists!")
        return old_username

    # Update JSON
    users[new_username] = users.pop(old_username)
    with open(users_file, "w") as f:
        json.dump(users, f)

    # Rename CSV
    old_file = f"{old_username}_expenses.csv"
    new_file = f"{new_username}_expenses.csv"
    if os.path.exists(old_file):
        os.rename(old_file, new_file)

    print("Username updated successfully!")
    return new_username

"""#**Step 6 – Login System (Login / Sign Up)**"""

def login_system():
    while True:
        print("\n1. Login")
        print("2. Sign Up")
        choice = input("Enter choice (1-2): ").strip()

        if choice == "1":
            user = login()
            if user:
                return user
        elif choice == "2":
            sign_up()
        else:
            print("Invalid choice! Try again.")

"""#**Step 7 – Load or Create User CSV**"""

def load_user_data(user):
    file_name = f"{user}_expenses.csv"
    if os.path.exists(file_name):
        df = pd.read_csv(file_name)
    else:
        df = pd.DataFrame(columns=["Date", "Category", "Description", "Amount"])
    return df, file_name

"""#**Step 8 – Add Expense**"""

def add_expense(expenses_df, file_name):
    date = input("Enter Date (YYYY-MM-DD): ")
    category = input("Enter Category: ")
    description = input("Enter Description: ")
    try:
        amount = float(input("Enter Amount: "))
    except:
        print("Invalid amount entered!")
        return expenses_df

    new_row = pd.DataFrame([[date, category, description, amount]], columns=expenses_df.columns)
    expenses_df = pd.concat([expenses_df, new_row], ignore_index=True)
    expenses_df.to_csv(file_name, index=False)
    print("Expense added successfully!")
    return expenses_df

"""#**Step 9 – View Expenses**"""

def view_expenses(expenses_df):
    if expenses_df.empty:
        print("No expenses recorded.")
    else:
        print("\nRecorded Expenses:")
        print(tabulate(expenses_df, headers="keys", tablefmt="fancy_grid", showindex=True))

"""#**Step 10 – Delete Expense**"""

def delete_expense(expenses_df, file_name):
    if expenses_df.empty:
        print("No expenses to delete.")
        return expenses_df

    view_expenses(expenses_df)
    try:
        idx = int(input("Enter the index of expense to delete: "))
        expenses_df = expenses_df.drop(idx).reset_index(drop=True)
        expenses_df.to_csv(file_name, index=False)
        print("Expense deleted successfully!")
    except:
        print("Invalid index. Please try again.")
    return expenses_df

"""#**Step 11 – Filter by Category**"""

def filter_by_category(expenses_df):
    if expenses_df.empty:
        print("No data available.")
        return

    category = input("Enter category to filter: ")
    filtered = expenses_df[expenses_df["Category"].str.lower() == category.lower()]

    if filtered.empty:
        print(f"No expenses found for category '{category}'.")
    else:
        print(tabulate(filtered, headers="keys", tablefmt="fancy_grid", showindex=False))

"""#**Step 12 – Monthly Summary**"""

def monthly_summary(expenses_df):
    if expenses_df.empty:
        print("No data available.")
        return

    df = expenses_df.copy()
    df["Date"] = pd.to_datetime(df["Date"])
    df["Month"] = df["Date"].dt.to_period("M")
    summary = df.groupby("Month")["Amount"].sum().reset_index()
    print("\n📊 Monthly Expense Summary:")
    print(tabulate(summary, headers="keys", tablefmt="fancy_grid", showindex=False))

"""#**Step 13 – Main App**"""

def main():
    user = login_system()  # Login or Sign Up
    expenses_df, file_name = load_user_data(user)

    while True:
        print(f"\n--- Personal Expense Tracker ({user}) ---")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Delete Expense")
        print("4. Filter by Category")
        print("5. Monthly Summary")
        print("6. Update Account")
        print("7. Exit")
        choice = input("Enter choice (1-7): ")

        if choice == "1":
            expenses_df = add_expense(expenses_df, file_name)
        elif choice == "2":
            view_expenses(expenses_df)
        elif choice == "3":
            expenses_df = delete_expense(expenses_df, file_name)
        elif choice == "4":
            filter_by_category(expenses_df)
        elif choice == "5":
            monthly_summary(expenses_df)
        elif choice == "6":
            print("\n1. Update Username")
            print("2. Update Password")
            sub = input("Enter choice (1-2): ")

            if sub == "1":
                user = update_username(user)
                expenses_df, file_name = load_user_data(user)
            elif sub == "2":
                update_password(user)
            else:
                print("Invalid choice for account update.")

        elif choice == "7":
            print(f"Thank you for using the Expense Tracker, {user}! Goodbye!")
            break
        else:
            print("Invalid choice! Please enter a number between 1 and 7.")

"""#**Step 14 – Run the App**"""

main()